---
title: "GEOSCHEM-NBE data summary"
output:
  html_document:
    css: styles.css
    df_print: paged
---
<style type="text/css">
.main-container {
  max-width: 2500px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```{r echo = FALSE, message=FALSE, warning=FALSE}
library(ncdf4); library(raster); library(dplyr);library(ggplot2);library(ggpubr);library(quantreg);library(ggpp);library(rgeos);library(ggpmisc);library(rgdal);library(Metrics);library(kableExtra)

```


Pixel-subset based analysis of assimilted Rainfor data into CARDAMOM DALEC
```{r echo = FALSE, message=FALSE, fig.asp = 0.5, fig.width = 25}
#load("R:/cssp_brazil/cssp_brazil_R/data/extracted_card.RData")
prefix_nbe <- 'R://ILAMB_beta_devel/RAINFOR_leeds_run/cssp_brazil_amazon_run/DATA/benchmark/Amazon_subset_'
suffix_nbe <- '_2000_updated_2019.nc'

prefix_new <- 'M://CARDAMOM/CARDAMOM/CARDAMOM_OUTPUTS/DALEC_CDEA_ACM2_BUCKET_MHMCMC/'
midfix <- '_subset/RESULTS_PROCESSED/'
suffix_new <- '_subset_stock_flux.RData'

source('R:/cssp_brazil/cssp_brazil_R/code/subset_pixel_functions_nbe_only.R') #imports plotting codes

amazonia_subset <- shapefile("R:/cssp_brazil/cssp_brazil_R/data/amazonia_subset.shp")
nbe_var_name <- c('NBE')
mod_var_nbe <- c('esa_cci_biomass_only','biomass_annual_productivity','esa_cci_agb_nbe','biomass_annual_productivity_nbe')

nbe_time_period <- c('2015_2019')
load("R:/cssp_brazil/cssp_brazil_R/data/nbe_benchmark_data.RData")

par(mfrow = c(2,2))
par(mfrow = c(2,2));res_df_merge_plot_nbe(amazonia_subset,nbe_var_name,mod_var_nbe,nbe_benchmark_data)
```

Pixel based analysis of assimilted Rainfor data into CARDAMOM DALEC
```{r echo = FALSE, message=FALSE, fig.asp = 0.9, fig.width = 20}
#load("R:/cssp_brazil/cssp_brazil_R/data/extracted_card.RData")
#source('R:/cssp_brazil/cssp_brazil_R/code/extract_resample_plot.R') #imports plotting codes
# source('R:/cssp_brazil/cssp_brazil_R/code/subset_pixel_functions.R') #imports plotting codes

mod_var_nbe_new <- c('esa_cci_agb_only','Rainfor_woody_biomass_annual_productivity',
                 'esa_cci_agb_nbe','Rainfor_woody_biomass_annual_productivity_nbe'
)
mod_var_abr_nbe <- c('default','benchmark','default_nbe','benchmark_nbe')
par_names <- c('Lit2SOM (day_1)','GPP%Ra','NPP_fol_frac','NPP_root_frac','Leaf lifespan','TO Wood','TO Roots','Mineralise Lit','SOM2Rh',
               'Temp fac','Canopy Eff (gC/m2leaf/day)','Max bud burst day','NPP_lab_frac','Labile_release_period','max leaf fall',
               'leaf fall period','LMA (gC/m2)','Labile_initial','Foliar_initial','Roots_initial','Wood_initial','Lit_initial',
               'SOM_initial','Soil Water_initial','Cwood_coarseR_frac','CoarseR Biomass 50% Max Depth','Max Root Depth',
               'Res factor Burned Cstocks','CCF Fol','CCF Wood and FineR','CCF Soil','CCF Fol and FineR Lit','unknown','model_var')

param_names <- c('model_var','Lit2SOM (day_1)','GPP%Ra','NPP_fol_frac','NPP_root_frac','Leaf lifespan','TO Wood','TO Roots','Mineralise Lit','SOM2Rh',
               'Temp fac','Canopy Eff (gC/m2leaf/day)','Max bud burst day','NPP_lab_frac','Labile_release_period','max leaf fall',
               'leaf fall period','LMA (gC/m2)','Labile_initial','Foliar_initial','Roots_initial','Wood_initial','Lit_initial',
               'SOM_initial','Soil Water_initial','Cwood_coarseR_frac','CoarseR Biomass 50% Max Depth','Max Root Depth',
               'Res factor Burned Cstocks','CCF Fol','CCF Wood and FineR','CCF Soil','CCF Fol and FineR Lit')

# model_pars_list <- list()
model_pars_nbe_df<-as.data.frame(t(data.frame(extract_parameters_all_models(mod_var_nbe_new,mod_var_abr_nbe))), stringsAsFactors = FALSE)
model_pars_nbe_df[] <- lapply(model_pars_nbe_df, type.convert, as.is = TRUE)
rownames(model_pars_nbe_df)<-  seq_along(model_pars_nbe_df[,1])
colnames(model_pars_nbe_df)<-  par_names
model_pars_nbe_df$model_var<-as.factor(model_pars_nbe_df$model_var)
model_pars_nbe_df<-model_pars_nbe_df[,c(34,1:32)]
model_pars_nbe_df$NPP_wood_frac<-1-(model_pars_nbe_df[,4]+model_pars_nbe_df[,5])
model_pars_nbe_df$rt_wood<-1/model_pars_nbe_df[,7]
model_pars_nbe_df$rt_roots<-1/model_pars_nbe_df[,8]
new_model_pars_nbe_df<-round_df(model_pars_nbe_df[,c(3,34,4,5,14,26,22,20,19,21,23,24,35,36)], 3)
rownames(new_model_pars_nbe_df)<-mod_var_abr_nbe
kable(new_model_pars_nbe_df) %>%
  kable_styling("striped", full_width = F) %>%
  scroll_box(width = "100%", height = "750px")
```
